version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  app:
    build: .
    container_name: file_service_app
    restart: always
    ports:
      - '3000:3000'
    networks:
      - app_network
    depends_on:
      - mysql
      - redis
  
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: file_service_db
    ports:
      - '3306:3306'
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app_network
    volumes:
      - redis_data:/var/lib/redis

volumes:
  mysql_data:
  redis_data:
